version: '3.8'

services:
  db:
    image: postgres:16.3-bullseye
    environment:
      POSTGRES_PASSWORD: olast
      POSTGRES_USER: olast
      POSTGRES_DB: olast
    volumes:
      - ./pgsql:/var/lib/postgresql/data
      - ./app/data/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./app/data/seeding.sql:/docker-entrypoint-initdb.d/seeding.sql
    expose:
      - "5432"
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PG_URL: postgres://olast:olast@db:5432/olast
    env_file:
      - .env
    volumes:
      - .:/app
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-timeout", "30s", "npm", "run", "dev"]

volumes:
  pgdata:
