GET http://localhost:3000/api/v1/games
###

GET http://localhost:3000/api/v1/posts/1


@endpoint=http://localhost:3000/api/v1

###get all users
GET {{endpoint}}/users

### get one user
GET {{endpoint}}/users/1

### Create a user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
"firstname": "Alexandre",
"lastname": "Hamed",
"email": "alexandrehamed@hotmail.fr",
"password": "pass",
"birth_date": "1990-05-14T22:00:00.000Z",
"discord_username": "JohnDoe#1234",
"city": "Noisy-le-roi"
}

### Update a user
PATCH http://localhost:3000/api/v1/users/4
Content-Type: application/json

{
"firstname": "AlexandreUpdatedbis"
}

### delete user
DELETE http://localhost:3000/api/v1/users/2

GET http://localhost:3000/api/v1/profil HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/api/v1/profil/1 HTTP/1.1

### Test POST request for creating a new profil
POST http://localhost:3000/api/v1/profil
Content-Type: application/json

{
  "name": "New Gamer",
  "description": "New player in League of Legends",
  "rank": "Silver",
  "level": 10,
  "game_id": 2,
  "user_id": 2
}
### Test PATCH request for updating a profil
PUT http://localhost:3000/api/v1/profil/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated Gamer"
 
}

### Test login user
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "hashed_password1"
}

###
DELETE http://localhost:3000/api/v1/rates/1
Authorization: Bearer 

### Get user datails
GET http://localhost:3000/api/v1/users/4/profil