GET http://localhost:3000/api/v1/games
###

GET http://localhost:3000/api/v1/posts/1


@endpoint=http://localhost:3000/api/v1

###get all users
GET {{endpoint}}/users

### get one user
GET {{endpoint}}/users/1

### Create a user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
"firstname": "Alexandzere1",
"lastname": "Hazmed1",
"email": "alexandrehamed@hotmail.fr",
"password": "mdp",
"birth_date": "1990-05-14T22:00:00.000Z",
"discord_username": "JohnaDoe#1234",
"city": "Noisy-lee-roi"
}

### Update a user
PATCH http://localhost:3000/api/v1/users/4
Content-Type: application/json

{
"firstname": "AlexandreUpdatedbis"
}

### delete user
DELETE http://localhost:3000/api/v1/users/2

###

GET http://localhost:3000/api/v1/profil HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3000/api/v1/profil/1 HTTP/1.1

### Test POST request for creating a new profil
POST http://localhost:3000/api/v1/profil
Content-Type: application/json

{
  "name": "New Gamer",
  "description": "New player in League of Legends",
  "rank": "Silver",
  "level": 10,
  "game_id": 2,
  "user_id": 2
}
### Test PATCH request for updating a profil
PUT http://localhost:3000/api/v1/profil/1 HTTP/1.1
Content-Type: application/json

{
  "name": "Updated Gamer"
 
}


### Test login user
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
  "email": "bla@bla",
  "password": "mdp"
}

###
DELETE http://localhost:3000/api/v1/rates/1
Authorization: Bearer 

### Get user datails
GET http://localhost:3000/api/v1/users/4/details

###forgot password generation de l'url
POST http://localhost:3000/api/v1/forgot-password
Content-Type: application/json

{
  "email":"alexandrehamed@hotmail.fr"
}

###new password form submission
POST  http://localhost:3000/api/v1/forgot-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsZXhhbmRyZWhhbWVkQGhvdG1haWwuZnIiLCJpYXQiOjE3MjA0NDc1MzMsImV4cCI6MTcyMDQ1NDczM30.nVvbPuAd16XIBGOlXI2puLGAb6vHg_7QL27_D5J99cs
Content-Type: : application/json

{
  "password":"nvxpasse"
}